version: '3'
services:
  mysite:
    image: jianchengwang/mysite:latest
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/tmp:/etc/mysite/_git
      - /root/files/tmp:/etc/mysite/tmp
    environment:
      APP_URL: "*"
      APP_PASSWORD: 123456
      APP_GIT_PATH: /etc/mysite/_git
      APP_TMP_PATH: /etc/mysite/tmp
      TENCENT_SECRET_ID:
      TENCENT_SECRET_KEY:
